config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :publics, only: [:index]
  resources :users do
    resources :foods, except: [:edit,]
    resources :recipes, except: [:edit] do
      resources :lists, only: [:new, :create, :destroy]
      resources :shops, only: [:index]
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.where(user_id: current_user.id)
    @user = User.find(params[:user_id])
  end

  def new
    @food = Food.new
  end

  def create
    food = Food.new(food_params)
    food.user_id = params[:user_id]

    if food.save
      redirect_to user_foods_path(params[:user_id])
    else
      redirect_to new_user_food_path
    end
  end

  def destroy
    @food = Food.find(params[:id]).destroy
    redirect_to user_foods_path(params[:user_id])
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def new
    @foods = Food.all
    @recipe_food = RecipeFood.new
  end

  def create
    recipe_food = RecipeFood.new(recipe_list_params)
    recipe_food.recipe_id = params[:recipe_id]

    if recipe_food.save
      redirect_to user_recipe_path(params[:user_id], params[:recipe_id])
    else
      puts 'error'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id]).destroy
    redirect_to user_recipe_path(params[:user_id], params[:recipe_id])
  end

  private

  def recipe_list_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
    @public = Recipe.includes(:user).where(public: true)
    @recipe_food = RecipeFood.all
    @food = Food.all
  end

  # def count
  #   @recipe_food = RecipeFood.find(:recipe_id params[:])
  # end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all
    @user = User.find(params[:user_id])
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.includes(:food).where(recipe_id: params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.new(recipe_params)
    recipe.user_id = params[:user_id]

    if recipe.save
      redirect_to user_recipes_path(params[:user_id])
    else
      redirect_to new_user_recipe_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    redirect_to user_recipes_path(params[:user_id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @recipe_food = RecipeFood.includes(:food).where(recipe_id: params[:recipe_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/foods_list_helper.rb
module FoodsListHelper
end

app/helpers/recipes_foods_helper.rb
module RecipesFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<h1>Food section</h1>


<table class= "food_table">
  <thead class= "head">
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @foods.each do |food| %>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%= food.price %></td>
      <td><%= button_to 'Delete', user_food_path(@user, food), method: :delete, class: "delete" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="btn_location">
  <%= link_to 'Add Food', new_user_food_path(@user), class: "link" %>
</div>

app/views/foods/new.html.erb
<h1>Add Food Section</h1>

<%= form_with model: @food, url: user_foods_path do |f| %> 
  <div class="form">
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'input' %>
    </div>
    <div>
    <%= f.label :measurement_unit %>
    <%= f.text_field :measurement_unit, class: 'input'%>
    </div>
    <div>
    <%= f.label :price %>
    <%= f.number_field :price, class: 'input' %>
    </div>
    <div>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: 'input' %>
    </div>

    <%= f.submit 'Add', class: "link food_btn" %>
  </div>
<% end %>  

app/views/home/index.html.erb
<div class="root">
  <h1>Click the button to access the information</h1>
</div>

<div class="links">
  <%= link_to 'Public recipes', publics_path, class: "link"%>

  <% if user_signed_in? %>
    <%= link_to 'Food list', user_foods_path(current_user.id), class: "link" %>
    <%= link_to 'Recipes', user_recipes_path(current_user.id), class: "link" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar", locals: {user: current_user} %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/new.html.erb
<h1>Add ingredients</h1>

<div class="add_food_table">
  <div class="title_columns">
    <h3>Food</h3>
    <h3>Measurement Unit</h3>
    <h3>Unit Price</h3>
    <h3>Quantity</h3>
    <h3>Actions</h3>
  </div>

  <% @foods.each do |food| %>
    <%= form_with model: @recipe_food, url: user_recipe_lists_path do |f| %> 
      <div class="rows">
        <h4><%= food.name %></h4>
        <h4><%= food.measurement_unit %></h4>
        <h4><%= food.price %></h4>
        <h4><%= f.number_field :quantity %></h4>
        <%= f.hidden_field :food_id, value: food.id %>
        <h4><%= f.submit 'Add', class: 'delete' %></h4>
      </div>
    <% end %>
  <% end %>
</div>

app/views/publics/index.html.erb
<h1>Public Recipes</h1>

<div class="cards">
  <% @public.each do |recipe| %>
  <div class="card">
    <% @result = 0 %>
      <div class="by">
        <h2><%= recipe.name %></h2>
        <h5>Created By: <%= recipe.user.email %></h5>
      </div>

      <div class="totals">
        <% @total_data = @recipe_food.where(recipe_id: recipe.id) %>
        <h5>Total Food Items: <%= @total_data.count %></h5>

        <% @total_data.each do |value| %>
          <% @total = @food.where(id: value.food_id).first %>
          <% @result += @total.price %>
        <% end %> 
        <h5>Total Price: <%= @result %></h5>
      </div>
  </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<h1>Recipes list</h1>

<ul class="cards">
  <% @recipes.each do |recipe| %>
    <li class="card card_recipe">
      <div class="recipe_name">
        <div><%= recipe.name %></div>

        <% if current_user.id == recipe.user_id %>
          <%= button_to 'Delete', user_recipe_path(@user, recipe), method: :delete, class: "delete" %>
        <% end %>
      </div>

      <div class="description">
        <p><%= recipe.description %></p>
        <%= link_to 'show Recipe', user_recipe_path(@user, recipe), class: "link_delete" %>
      </div>
    </li>
  <% end %>
</ul>

<div class="btn_location">
  <%= link_to 'Add Recipe', new_user_recipe_path(@user), class: 'link'%>
</div>

app/views/recipes/new.html.erb
<h1>Recipe</h1>

<%= form_with model: @recipe, url: user_recipes_path do |f| %> 
  <div class="form">
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'input' %>
    </div>
    <div>
      <%= f.label :preparation_time %>
      <%= f.number_field :preparation_time, class: 'input' %>
    </div>
    <div>
      <%= f.label :cooking_time %>
      <%= f.number_field :cooking_time, class: 'input' %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'input area' %>
    </div>
    <div>
      <%= f.label :public %>
      <%= f.radio_button :public, "public", class: 'public_checker' %>
    </div>

    <%= f.submit 'Add', class: "link food_btn" %>
  </div>
<% end %>  

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<div class="recipe_info">
  <div class='preparation'>
    <div class='time'>
      <div>
        Preparation Time: <%= @recipe.preparation_time %>h
      </div>
      <div>
        Cooking Time: <%= @recipe.cooking_time %>h
      </div>
      <div>
        Steps:
        <p><%= @recipe.description %></p>
      </div>
    </div>
    <div>
      <%= link_to 'Generate shopping list',  user_recipe_shops_path(current_user.id, @recipe.id), class: 'btnOne ' %>
    </div>
  </div>

  <div class='more_details'>
    <div>
      is it public? <%= @recipe.public %>
    </div>

    <% if current_user.id == @recipe.user_id %>
      <div>
        <%= link_to 'Add Food', new_user_recipe_list_path(@recipe.user_id, @recipe.id), class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

<table class= "food_table">
  <thead class= "head">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value $</th>
      <th>ID</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe_food.each do |rec| %>
      <tr>
        <td><%= rec.food.name %></td>
        <td><%= rec.quantity %></td>
        <td><%= rec.food.price %></td>
        <td><%= rec.id %></td>
        <td><%= button_to 'Delete', user_recipe_list_path(@recipe.user_id, @recipe.id, rec.id), method: :delete, class: "delete" %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

app/views/shared/_navbar.html.erb
<div class="navbar">  
  <% if user_signed_in? %>
    <div class="welcome">
      Welcome:
      <p><%= user.email %>!</p>
    </div>
    <div class="home">
      <%= link_to 'Home', root_path, class: "access" %>
    </div>
    <div class="out">
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "access out_btn" %>
    </div>
  <% else %>
    <div class="in">
      <%= link_to 'Sign up', new_user_registration_path, class: "access" %>
      <%= link_to 'Log in', new_user_session_path, class: "access" %>
    </div>
  <% end %>
</div>

app/views/shops/index.html.erb
<h1>Shopping list</h1>

<div class="shop_table">
  <div class="shop_title">
    <h3>Food</h3>
    <h3>Quantity</h3>
    <h3>Price</h3>
  </div>

  <% @total = 0 %>

  <% @recipe_food.each do |rec| %>
    <div class="shop_info">
      <div class="shop_rows">
        <h4><%= rec.food.name %></h4>
        <h4><%= rec.quantity %></h4>
        <h4><%= rec.food.price %></h4>
        <% @total += rec.food.price %>
      </div>
    <div>
  <% end %>
</div>


<div class="totals">
  <div>Amount of food items to buy: <%= @recipe_food.count %></div>
  <div>Total value of food needed: $<%= @total %></div>
</div>